### ISSUE TITLE
xz cannot be installed due to readlink illegal option --  f error on OS X. 

### ISSUE THREAD

**Issue by wavewave** [wavewave/hep-nix-overlay#16]
As we see from http://higgs.snu.ac.kr:8080/build/297/nixlog/1  
any packages dependent on xz cannot be now installed. 
This behavior is known. 
https://github.com/NixOS/nixpkgs/issues/3354
https://github.com/NixOS/nixpkgs/issues/3641

How can we circumvent this problem?

**Comment by cbpark** [comment]
`readlink` is in `coreutils`. The problem is that the GNU coreutils is different from BSD coreutils. In MacPorts, the problem was solved by having two coreutils, but with the name prefix. For example, GNU readlink is `greadlink`. See

* [bash-completion needs gnu readlink, not bsd](https://trac.macports.org/ticket/21877)

How about inhering `coreutils` in the nix expression for `xz`?

**Comment by wavewave** [comment]
Thanks for the investigation.
Let's try that fix as you suggested.

best,
IW

**Comment by wavewave** [comment]
This problem has been dealt with by NixOS/nixpkgs master now.
